variables:
  GIT_SUBMODULE_STRATEGY: recursive

image: ubuntu:18.04

stages:
  - test


before_script:
    - echo "Install apt packages..."
    - apt update -qq
    # - apt -qq -y install lsb
    - apt -qq -y install g++
    - apt -qq -y install cmake
    - apt -qq -y install sox
    - apt -qq -y install wget
    # - apt -qq -y install pip

    # - lsb_release -a
    - uname -a
    - cmake --version

    - if [ ! -d $HOME/miniconda/bin ] ; then
            echo "Install Miniconda";
            mkdir -p $HOME/download;
            wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O $HOME/download/miniconda.sh;
            bash $HOME/download/miniconda.sh -u -b -p $HOME/miniconda;
        fi
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda update --yes conda
    - conda install --yes pip
    - conda info -a

    - echo "Install conda packages..."
    - conda install --yes cython=0.26.1 libffi=3.2.1 libgcc-ng=7.2.0 libstdcxx-ng=7.2.0 numpy=1.12.1 scipy=0.19.1 mako=1.0.6 theano=0.9.0 # TODO Really need mako ?
    - conda install --yes matplotlib=2.0.2 # Has to be done separately otherwise conda crashes

    - echo "Install pip packages..."
    - pip install codecov
    - pip install codacy-coverage
    - pip install defusedxml
    - pip install bandmat

test:
  stage: test
  script:
    - pwd
    - ls -l

    - make
    - cd percivaltts
    - tar xvf tests/slt_arctic_merlin_test.tar.gz -C tests/
    - coverage run --source=. --omit="tests/*","external/*" -m tests.test_base
    - coverage run -a --source=. --omit="tests/*","external/*" -m tests.test_smoke
    - bash setenv_travis.sh coverage run -a --source=. --omit="tests/*","external/*" -m tests.test_smoke_theano
    - bash setenv_travis.sh coverage run -a --source=. --omit="tests/*","external/*" -m tests.test_run
